name: CI/CD Java Class Library

on:
  push:

jobs:
  call-build:
    uses: ./.github/workflows/reusable-ci-java.yaml
    with:
      app-path: ./src-java-classlib
      
  deploy:
    needs: call-build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: build-artifact
        path: ./output

    - uses: s4u/maven-settings-action@v3.0.0
      with:
        servers: '[{"id": "github", "username": "${{ github.actor }}", "password": "${{ secrets.GITHUB_TOKEN }}"}]'

    - name: Publish to GitHub Packages
      run: |
        mvn deploy:deploy-file -Dfile=./output/demo-classlib-0.0.1-SNAPSHOT.jar -DgroupId=com.example.avareview -DartifactId=demo-classlib -Dversion=0.0.1-SNAPSHOT -Dpackaging=jar -DrepositoryId=github -Durl=https://maven.pkg.github.com/andrediasbr/ava-dojo-review01