name: cicd-dotnet

on: 
  push:
    branches:
      - main/*
 
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET Core  
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Dotnet Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Publish
      run: dotnet publish --configuration Release --no-restore --output ./dojo

    # - name: upload artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: .net-app
    #     path: ./publish