name: cicd-dotnet
on: workflow_dispatch
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET Core  
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x