name: CI/CD Java Web Api

on:
  push:
    paths:
      - 'src-java-webapi/**'

jobs:
  call-build:
    uses: ./.github/workflows/reusable-ci-java.yaml
    with:
      app-path: ./src-java-webapi
      
  deploy:
    needs: call-build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./output

      #incluir tasks de container
