name: cicd-dotnet

on: 
  workflow_dispatch:
    inputs:
      dotnet-version:
        type: string
        description: 'Versão usada pelo .NET'
        default: '8.0.x'
      app-version:
        type: string
        description: Versão da Aplicação
        default: '1.0.0'
      path:
        type: string
        description: 'Caminho do aplicativo .NET'
        default: './src-classlib'

env:
  GH-REG: ghcr.io

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET Core  
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
    
    - name: Dotnet Restore
      run: dotnet restore ${{ inputs.path }}

    #- name: Sonar Scan
    #  uses: sonarsource/sonarqube-scan-action@<2.3.0
    #  env:
    #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #    SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

    - name: Build
      run: dotnet build ${{ inputs.path }} --configuration Release --no-restore
    
    - name: Test
      run: dotnet test ${{ inputs.path }} --no-restore --verbosity normal

    - name: Publish
      run: dotnet publish ${{ inputs.path }} --Property:Version=${{ inputs.app-version }} --configuration Release --no-restore --output ./output

    - name: EMpacotamento
      run: dotnet pack  ${{ inputs.path }} --configuration Release --no-build --output ./pacote 

    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: .net-app
        path: ./output
    
    # - name: add source 
    #  run:  dotnet nuget add source --username ${{github.actor}} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/andrediasbr/index.json"

    - name: Send to registry
      run: dotnet nuget push ./pacote/*.nukpkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/andrediasbr/index.json"
     